---
- hosts: monitoring
  roles:
    - role: cloudalchemy.prometheus
      vars:
        prometheus_targets:
          node:
            - targets:
                - localhost:9100
                - result.aruniq.ir:9100
                - result.aruniq.ir:8086
                - worker.aruniq.ir:9100
                - result.aruniq.ir:9121
                - worker.aruniq.ir:9187
              labels:
                env: demosite
    - role: cloudalchemy.node_exporter
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin_admin
      roles:
    - role: patrickjahns.promtail
      vars:
        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
              - targets:
                  - localhost
                labels:
                  host: "monitoring"
                  job: varlogs
                  __path__: /var/log/*log
        promtail_loki_server_url: "http://localhost:3100"

    - role: ansible-loki
      vars:
        loki_version: "2.4.2"
        loki_base_dir: /opt/loki
      become: true
- hosts: worker
  become: true
  roles:
    - role: commons
    - role: postgres
      gather_facts: False
      vars:
        postgres_root_user: root
        postgres_root_pass: 123456
        db_name: "vote"
        allow_world_readable_tmpfiles: true
    - role: worker
    - role: cloudalchemy.node_exporter
    - role: patrickjahns.promtail
      vars:
        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
              - targets:
                  - localhost
                labels:
                  host: "worker"
                  job: varlogs
                  __path__: /var/log/*log
        promtail_loki_server_url: "http://grafana.aruniq.ir:3100"

- hosts: master
  become: true
  roles:
    - role: commons
    - role: nginx
    - role: redis
      vars:
        redis_password: 123456
    - role: vote
    - role: result
    - role: cloudalchemy.node_exporter
    - role: patrickjahns.promtail
      vars:
        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
              - targets:
                  - localhost
                labels:
                  host: "vote"
                  job: varlogs
                  __path__: /var/log/*log
        promtail_loki_server_url: "http://grafana.aruniq.ir:3100"
