---
- hosts: master
  become: true

  roles:
    - role: commons
    - role: nginx
    - role: redis
      vars:
        redis_password: 123456
    - role: vote
    - role: result
- hosts: worker
  become: true
  roles:
    - role: commons
    - role: postgres
      gather_facts: False
      vars:
        postgres_root_user: root
        postgres_root_pass: 123456
        db_name: "vote"
        allow_world_readable_tmpfiles: true
    - role: worker
