---
- name: clone python vote app
  ansible.builtin.git:
    repo: "https://hamgit.ir/shahriarvelayat/vote.git"
    dest: /home/ubuntu/vote
    clone: yes

- name: install pip requirments
  pip:
    requirements: /home/ubuntu/vote/requirements.txt

- name: install pip gunicorn
  pip:
    name: gunicorn

- name: copy gunicorn configuration
  ansible.builtin.copy:
    src: ../templates/vote.service
    dest: /etc/systemd/system/vote.service
    force: yes
  notify:
    - Restart Vote-app
    - Enable Vote-app
